# Project information
site_name: Guide utilisateur CollectiveAccess
site_description: 'Documentation pour les utilisateurs de CollectiveAccess avec le plugin Musées De France'
site_author: 'idéesculture'

pages:
- Accueil: index.md
- Guide utilisateur Providence:
    - 1. Introduction: chapter1.md
    - 2. Structure de la base de données: chapter2.md
    - 3. Connexion et démarrage dans Providence: chapter3.md
    - 4. La gestion des recherches: chapter4.md
    - 5. Création d’un affichage personnalisé: chapaffichage.md
    - 6. Création d’un formulaire de recherche avancée: chapformrech.md
    - 7. La saisie d'un objet dans CollectiveAccess: chapter5.md
    - 8. La saisie d'une entité dans CollectiveAccess: chapter6.md
    - 9. La saisie des lieux dans CollectiveAccess: chapter7.md

# Repository
repo_name: 'GitHub'
repo_url: 'http://ideesculture.github.io/guide-utilisateur-collectiveaccess'

theme:
  name: material

# Options
extra:
  version: '1.0'
  logo: 'images/logo.png'
  author:
    github: 'ideesculture'
    twitter: 'ideesculture'
  faq:
    url: 'https://ideesculture.zendesk.com/hc/fr'

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: '¶'